services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - rag_network
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      uvicorn api.app:app --host 0.0.0.0 --port 8001 --reload

  qdrant:
    image: qdrant/qdrant:latest
    networks:
      - rag_network
    ports:
      - "6333:6333"

networks:
  rag_network:
    external: true
