services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./templates:/app/templates
      - ./requirements.txt:/app/requirements.txt
    networks:
      - rag_network
    environment:
      - PYTHONUNBUFFERED=1  # Ускорение вывода в консоль

networks:
  rag_network:
    external: true
